[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "yarn"]
aptPkgs = []

[phases.install]
cmds = [
  "bash -c 'cd backend && pip install -r requirements.txt'",
  "bash -c 'cd frontend && yarn install'"
]

[phases.build]
cmds = [
  "cd frontend && yarn build"
]

