[phases.setup]
nixPkgs = ["python311", "nodejs_18", "yarn"]

[phases.install]
cmds = [
  "source /etc/profile && cd backend && pip install -r requirements.txt",
  "source /etc/profile && cd frontend && yarn install",
]

[phases.build]
cmds = [
  "source /etc/profile && cd frontend && yarn build",
]

[start]
cmd = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
